import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :playa_web, PlayaWeb.Endpoint,
  # IMPORTANT:
  # 웹소켓 접속 체크에 사용되며 한 개의 IP로만 설정할 수 있음
  # Public IP 또는 Private IP 중 선택 입력
  url: [host: "125.180.50.132", port: 4000],
  cache_static_manifest: "priv/static/cache_manifest.json",
  # IMPORTANT: 릴리스 빌드할 때 반드시 설정해야 함
  server: true

# Configures Swoosh API Client
config :swoosh, :api_client, Playa.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
