#!/bin/sh

set -e

export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $ADDITIONAL_USER WITH PASSWORD '$ADDITIONAL_PASSWORD';
  CREATE DATABASE $ADDITIONAL_DB;
  GRANT ALL PRIVILEGES ON DATABASE $ADDITIONAL_DB TO $ADDITIONAL_USER;
EOSQL

export PGPASSWORD=$ADDITIONAL_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$ADDITIONAL_USER" --dbname "$ADDITIONAL_DB" <<-EOSQL
  CREATE SCHEMA $ADDITIONAL_SCHEMA AUTHORIZATION $ADDITIONAL_USER;
  GRANT ALL PRIVILEGES ON SCHEMA $ADDITIONAL_SCHEMA TO $ADDITIONAL_USER;
EOSQL